# Generated by Django 3.2.12 on 2022-03-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmedia", "0004_duration_optional_floatfield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"permissions": [("choose_media", "Can choose media")]},
        ),
    ]
